// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDghAWjfgfJY4sS07OVg8p0no3A2eJ7AVg',
    appId: '1:324232073611:web:1f2ffd607f5c38c2b31f8e',
    messagingSenderId: '324232073611',
    projectId: 'flutterprovider-6f602',
    authDomain: 'flutterprovider-6f602.firebaseapp.com',
    storageBucket: 'flutterprovider-6f602.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChfxlrFx7OR0aBASmQ_G7LZLhVjJKyk5s',
    appId: '1:324232073611:android:1972c053cf3a3483b31f8e',
    messagingSenderId: '324232073611',
    projectId: 'flutterprovider-6f602',
    storageBucket: 'flutterprovider-6f602.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKMxd8OYaHERJGSSzQURhRUZ1WrjHV0gQ',
    appId: '1:324232073611:ios:0e33d8946e6e6c22b31f8e',
    messagingSenderId: '324232073611',
    projectId: 'flutterprovider-6f602',
    storageBucket: 'flutterprovider-6f602.appspot.com',
    iosClientId:
        '324232073611-j7s73b6bl5lt6o3r4h0emhlsoee0sm71.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterprovider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKMxd8OYaHERJGSSzQURhRUZ1WrjHV0gQ',
    appId: '1:324232073611:ios:0e33d8946e6e6c22b31f8e',
    messagingSenderId: '324232073611',
    projectId: 'flutterprovider-6f602',
    storageBucket: 'flutterprovider-6f602.appspot.com',
    iosClientId:
        '324232073611-j7s73b6bl5lt6o3r4h0emhlsoee0sm71.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterprovider',
  );
}
